name: Release

on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: dbmate
        env:
          COMMITTER_TOKEN: ${{ secrets.RELEASE_TOKEN }}
